### ISSUE TITLE
Add support for JS

### ISSUE THREAD

**Issue by guyluz11** [point-source/dart_ping#15]
We are missing support for JS.

![image](https://user-images.githubusercontent.com/9304740/130207414-c44f7387-0bb6-438e-a4c9-77073241856a.png)

![image](https://user-images.githubusercontent.com/9304740/130208956-111c1400-ab0b-448e-9230-1362605c3643.png)

Can we add support for it?.

**Comment by point-source** [comment]
As far as I am aware, this is not currently possible. There are a couple methods that people can use to fake it / simulate it, but I don't believe there is a way to send a true ICMP echo packet over a local network from a browser via js. This is due to a couple of reasons:

- Not all browsers (if any) support low-level/raw data communication with the system's network card(s)
- Most operating systems require root privilege in order to send echo packets
- Most browsers prevent js code from running with elevated privilege

For additional context, another user [asked me about this here](https://github.com/point-source/dart_ping/issues/10#issuecomment-825314677) and we discussed this for a bit.

Finally, something _you can do_, is make a network request against the network device in question and report if it succeeds / connects or not. If you know for sure that the device is designed to reply as well as which port it expects to receive requests on, this can work. If you are just trying to perform a network scan, this will likely fail since most devices do not run arbitrary web servers on arbitrary ports.

If you have an idea about how we can workaround or otherwise implement this feature, I'm happy to consider it. Thanks!

**Comment by guyluz11** [comment]
Thank you for your detailed reply, for now I will close this issue as I understand that it is not possible.

In my case **I am** doing the request to a server in the same network with a specific port open, so I will reopen this issue in case I have more questions about how to pig to it.

Thanks
