### ISSUE TITLE
Readme for the repo is missing

### ISSUE THREAD

**Issue by guyluz11** [point-source/dart_ping#18]
Know that this repo has small readmes in each folder, but I think a big repo for all the projects is needed as well.

Even if it with a little amount of info the readme should state the general purpose of this repo, provide a link to [pub.dev page of this package](https://pub.dev/packages/dart_ping), and direct you to the folders with links.

I am not sure about that but I think that there is a way to combine both projects (dart_ping and dart_ping_ios) with conditional imports and have one big project which will also have one readme.

![image](https://user-images.githubusercontent.com/9304740/149664875-c2c2ff33-83a2-48b7-a63e-ed1900eb8645.png)

**Comment by point-source** [comment]
I agree regarding the readme. Will work on that. As for combining both projects, the issue is that the ios one requires either method channels or dart:ffi. Method channels are a flutter feature while ffi depends on an external binary.

In order to include the external binaries on an iOS build, the xcode project or podfile needs to specify them. A pure dart library has no way of doing this automatically. So the available options are:

- Combine the packages and drop native dart support (package become flutter only)
- Use dart ffi but don't include the binaries. Require iOS devs to manually locate / add / import the binaries to their project
- Keep the packages separate. dart_ping supports everything except web and iOS while dart_ping_ios adds iOS support but forces the flutter sdk to be included.

The first option would make this package effectively the same as [flutter_icmp_ping](https://pub.dev/packages/flutter_icmp_ping) so there's really no point. (Also, I wrote this because I needed native dart support)

The second option is more steps than importing dart_ping_ios so I don't know who it would be solving a problem for.

**Comment by guyluz11** [comment]
Thanks for the explanation.

So as you just said let's do only the readme part
