### ISSUE TITLE
windows ping release 

### ISSUE THREAD

**Issue by m2faridi** [point-source/dart_ping#22]
hi
windows app release show console application
for debug is good
pls fix this bug

**Comment by ZoubairDaddow** [comment]
also for me 

![image](https://user-images.githubusercontent.com/32312290/160424186-a1bbb965-7f3b-45ae-832f-751d6b496bf0.png)

**Comment by point-source** [comment]
I don't understand what you are asking. What is the behavior you are experiencing to see?

Have you read the windows section of the readme?

**Comment by ZoubairDaddow** [comment]
When we use dart_ping in windows and build the application using 
flutter build windows
the ping window appears (just in release mode)
when we run in debuge mode it doesn't appear

**Comment by ZoubairDaddow** [comment]
> When we use dart_ping in windows and build the application using flutter build windows the ping window appears (just in release mode) when we run in debuge mode it doesn't appear

`  dart_ping: ^6.1.1`

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1266], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.8)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability`

**Comment by m2faridi** [comment]
pls fix this bug

**Comment by point-source** [comment]
Guys, this is covered in the [Windows Compatibility](https://github.com/dart-lang/sdk/issues/39945#issuecomment-870428151) section of the readme and there is a workaround there. This is a flutter bug, not a dart_ping bug and there is nothing I can do to the dart_ping package to prevent it. You need to apply the workaround in every flutter app you use this library with. That's why it's in the readme.

I'm closing this issue since there is a documented fix available that I have verified to be working.
