### ISSUE TITLE
loop to test CDNs

### ISSUE THREAD

**Issue by nicolasvahidzein** [point-source/dart_ping#3]
I would like to know how to loop through a list of domains i am pinging to check the response time and see which one is the fastest.

I am having errors when i try to loop, any idea how i would do that with your package?

**Comment by point-source** [comment]
The simplest way to do this would be with a list and map() method:

import 'package:dart_ping/dart_ping.dart';

```
void main() async {
  var domains = [
    'google.com',
    '1.1.1.1',
    '8.8.8.8',
    'wikipedia.com',
    '127.0.0.1'
  ];

  List<Future<PingData>> pings = domains.map((e) => Ping(e, count: 1).stream.first);
  List<PingData> results = await Future.wait(pings);

  print(results);
}
```

That said, if you have more than say 5 domains that you want to check, I would probably use something like [Pool](https://pub.dev/packages/pool) to rate limit them so that you don't spawn a ton of processes on the host OS. You could use something like mapAsync() to make sure they only fire one at a time but assuming you care about performance, you'll want to batch and throttle the operations and pool lets you do this in an optimal way.

**Comment by nicolasvahidzein** [comment]
Thank you. The mean values of the pings aren't reflected in the values of the results.

Ill paste here my approach tomorrow. 
_________________________________
Nicolas Zein
 
***@***.***
(+242) 06-602-02-37

On Apr 7, 2021, at 01:20, PointSource ***@***.***> wrote:

﻿
The simplest way to do this would be with a list and map() method:

import 'package:dart_ping/dart_ping.dart';

void main() async {
  var domains = [
    'google.com',
    '1.1.1.1',
    '8.8.8.8',
    'wikipedia.com',
    '127.0.0.1'
  ];

  List<Future<PingData>> pings = domains.map((e) => Ping(e, count: 1).stream.first);
  List<PingData> results = await Future.wait(pings);

  print(results);
}
That said, if you have more than say 5 domains that you want to check, I would probably use something like Pool to rate limit them so that you don't spawn a ton of processes on the host OS. You could use something like mapAsync() to make sure they only fire one at a time but assuming you care about performance, you'll want to batch and throttle the operations and pool lets you do this in an optimal way.

**Comment by point-source** [comment]
Did you ever get this working?

**Comment by nicolasvahidzein** [comment]
Not yet. Im working on this today.

**Comment by nicolasvahidzein** [comment]
i get the following error:

_TypeError (type 'MappedListIterable<String, Future<PingData>>' is not a subtype of type 'List<Future<PingData>>')

on this line:

List<Future<PingData>> pings = domains.map((e) => Ping(e, count: 1).stream.first);

**Comment by point-source** [comment]
Try `List<Future<PingData>> pings = domains.map((e) => Ping(e, count: 1).stream.first).toList();`

**Comment by nicolasvahidzein** [comment]
i get these errors again

_Exception (Exception: Ping process exited with code: 2)
_Exception (Exception: Ping process exited with code: 1)

**Comment by point-source** [comment]
That's because the ping process on the host os is exiting with an error. So either the host can't be reached, the dns name can't be resolved, etc etc. Technically, this is intended behavior but since it seems to be confusing everyone, I have changed it in version 5.1.0 so that it only throws errors when it can't figure out what the error was. Otherwise, it just reports the error as part of the PingSummary.

**Comment by nicolasvahidzein** [comment]
ok understood, it was passing a malformed domain. Thank you i understand it better now.

The strange thing now is that the ping values do not make sense. I have a local ip address that pings at below 1 ms that shows up in your report as 400 ms. What do you think that could be due to?

**Comment by nicolasvahidzein** [comment]
I also get now error -13:
_Exception (Exception: Ping process exited with code: -13)

**Comment by nicolasvahidzein** [comment]
> ok understood, it was passing a malformed domain. Thank you i understand it better now.
> 
> The strange thing now is that the ping values do not make sense. I have a local ip address that pings at below 1 ms that shows up in your report as 400 ms. What do you think that could be due to?

i guess this was maybe due to the fact that it was only one ping, when i changed to 5 or 9 the median value was more realistic.

**Comment by point-source** [comment]
Can you post some example output? Feel free to redact the host if it's private. There shouldn't be a 400ms discrepancy between standard ping in terminal and ping with this library (assuming you are pinging between the same two systems). Are you using an android terminal emulator to test the ping or something else?

**Comment by nicolasvahidzein** [comment]
sadly i am not able to use any of your more recent releases

I/flutter (17161): PingData(response:PingResponse(seq:0, ip:192.168.2.5, ttl:128, time:161.0 ms), summary:null, error:null)

i'm pinging from my laptop and using your package to compare.

**Comment by nicolasvahidzein** [comment]
ok so i had to test individual pings and i get this:

I/flutter (17161): PingData(response:PingResponse(seq:0, ip:192.168.2.5, ttl:128, time:1.57 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:1, ip:192.168.2.5, ttl:128, time:7.16 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:2, ip:192.168.2.5, ttl:128, time:9.87 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:3, ip:192.168.2.5, ttl:128, time:3.23 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:4, ip:192.168.2.5, ttl:128, time:1.7 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:5, ip:192.168.2.5, ttl:128, time:8.77 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:6, ip:192.168.2.5, ttl:128, time:9.98 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:7, ip:192.168.2.5, ttl:128, time:3.25 ms), summary:null, error:null)
I/flutter (17161): PingData(response:PingResponse(seq:8), summary:null, error:PingError.RequestTimedOut)
I/flutter (17161): PingData(response:PingResponse(seq:9, ip:192.168.2.5, ttl:128, time:27.7 ms), summary:null, error:null)

45.53 total response times

if i divide by the number of successful pings i get: 5.05 ms but your mean is: 27.7 which does not match, even if we divide by 10 (total pings successful and timeouts) we get 4.5 ms which is even lower.

There seems to be an issue, can you explain to be how the mean is done?

**Comment by nicolasvahidzein** [comment]
in the past i also used to have the first ping coming in at 500 ms which would skew all the results.

**Comment by point-source** [comment]
Pinging from a laptop would not be a sufficient comparison since your laptop likely has more powerful cpu, wireless chip, larger antenna, possibly hardwired, etc. It is almost always going to perform better than pinging from a phone or emulator. To properly compare, download a "terminal emulator" from the play store and use the ping command in there.

Also, dart_ping does not report a mean at all. Each "time" value is the roundtrip time for that specific packet and has no relation to previous or later ping responses. You'll have to calculate a mean manually by storing and combining all ping responses. Based on the responses in your message above, the mean would actually be 8.14ms. 

sum(1.57, 1.7, 3.23, 3.25, 7.16, 8.77, 9.87, 9.98, 27.7) / 9 = 8.14ms. You can count the timeout however makes sense for you.

That said, having an average of 5ms from a laptop vs 8ms from a phone seems pretty normal to me. Might be a little on the long side but without knowing the technical circumstances around your hardware, testing method, and line speed, it would be impossible to say.

**Comment by point-source** [comment]
> sadly i am not able to use any of your more recent releases

@nicolasvahidzein I have created a new branch called "unsafe" which contains the most recent version of dart_ping (5.2.0) without nullsafety. It requires a min dart sdk of 2.9.0 so hopefully that works for you. You can use it in your pubspec like so:

```
dependencies:
  dart_ping:
    git:
      url: https://github.com/point-source/dart_ping
      ref: unsafe
```

**Comment by nicolasvahidzein** [comment]
Hello, sadly i was not able to update just yet to your nullsafe version you created for me but i am very thank full for your time. I hopefully will be able to update it soon. Your help has been very useful. Thank you once again.

**Comment by nicolasvahidzein** [comment]
I spoke too fast, I was able to load the null safe version. Thanks a ton. I will test it and let you know. Cheers.

**Comment by group2tts** [comment]
> Самый простой способ сделать это — использовать список и метод map():
> 
> импортировать 'package:dart_ping/dart_ping.dart';
> 
> ```
> void main() async {
>   var domains = [
>     'google.com',
>     '1.1.1.1',
>     '8.8.8.8',
>     'wikipedia.com',
>     '127.0.0.1'
>   ];
> 
>   List<Future<PingData>> pings = domains.map((e) => Ping(e, count: 1).stream.first);
>   List<PingData> results = await Future.wait(pings);
> 
>   print(results);
> }
> ```
> 
> Тем не менее, если у вас есть более, скажем, 5 доменов, которые вы хотите проверить, я бы, вероятно, использовал что-то вроде [Pool](https://pub.dev/packages/pool) , чтобы ограничить их скорость, чтобы не порождать кучу процессов на хостовой ОС. Вы можете использовать что-то вроде mapAsync(), чтобы убедиться, что они запускаются только по одному за раз, но, предполагая, что вы заботитесь о производительности, вы захотите пакетировать и регулировать операции, и pool позволяет вам делать это оптимальным образом.
