### ISSUE TITLE
What do each of the thrown exit codes mean?

### ISSUE THREAD

**Issue by nicolasvahidzein** [point-source/dart_ping#7]
So we don't confuse the threads, can you please explain what are the different error codes?

i have seen, 1 and 2, and now 13. 

Thank you for your assistance.

**Comment by point-source** [comment]
Thanks for splitting this out into a different issue. These are exit codes from the host OS and the native ping binary. I don't have control over those, all I can do is report what I get from them. When the ping binary runs on your system (outside of and unrelated to dart), it will exit with either 0 (success) or some number greater than 0. Exit code 1 means "No Reply" on both linux and macOS but on Windows, it just means "some kind of error happened". This makes it very difficult to report in a helpful way since the OS is being very vague about what happened. It's generally up to the user to interpret the output from the process just before it exited.

I have written dart_ping to make a best-effort attempt to decipher what the exit code means based on the ping process output. Unfortunately, some codes (like code 2 on macOS and code 1 on Windows) do not provide enough information about what went wrong for me to report anything other than "Exited with code $code". I wish things could be more clear here but they aren't dart issues or architecture issues at this point, they extend to the underlying ping process.

Hopefully that helps clear things up. Let me know if you need more clarification on any part of that. Here's a quick reference:

- Linux
    - 0: Success
    - 1: No Reply
    - \>=2: Unknown Error

- macOS
    - 0: Success
    - 1: No Reply
    - 68: Unknown Host
    - \>=2 < 68: Unknown Error
    - \>68: Unknown Error

- Windows
    - 0: Success
    - 1: Unknown Error

If you get on of these codes and dart_ping throws an error but running the equivalent command in the terminal would output better info, open an issue so I can teach dart_ping to properly parse the error output.

**Comment by nicolasvahidzein** [comment]
Thank you so much for this detailed response. That is great insight. Ill look through this attentively. My fiber internet is down So i can’t work right now but i will be able to test this by tonight.
